import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/lib/theme-provider";
import { GeistMono } from 'geist/font/mono';
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./navbar";


export const metadata: Metadata = {
  title: "Ziel",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistMono.className} justify-center flex items-center flex-col`}>
        <div className="background">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
          </ThemeProvider>
          <Toaster></Toaster>
        </div>
      </body>
    </html>
  );
}
